# Generated by Django 5.1.2 on 2024-11-29 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_webapp', '0002_authors_feedback_topartist_toptrack'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='expiration_time',
            field=models.IntegerField(default=0),
        ),
    ]
